version: '3.8'

services:
  kommo-n8n-app:
    build: .
    container_name: kommo-n8n-integration
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./nginx.conf:/etc/nginx/sites-available/default
      - ./ssl:/etc/letsencrypt
    networks:
      - kommo-n8n-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kommo-n8n-network:
    driver: bridge

volumes:
  logs:
  ssl:
